### ISSUE TITLE
my project eashyshowview docsets is 404

### ISSUE THREAD

**Issue by chenliangloveyou** [CocoaPods/cocoadocs.org#573] opened 2017-12-29 01:27 UTC
sit : http://cocoadocs.org/docsets/EasyShowView/1.0.0

**Comment by Sorix** [comment] 2018-01-01 12:15
duplicate of #572

**Comment by orta** [comment] 2018-01-09 15:36
Hi there, CocoaDocs was shut down back in [early 2017](http://blog.cocoapods.org/CocoaDocs-Documentation-Sunsetting/) and has been slowly stopping support for new projects. At some point we plan on making a notification on all pages about the shutdown, but for now your issue is likely to be unresolved by anyone.

**Closed by orta** 2018-01-09 15:36 UTC
