### ISSUE TITLE
Request to update to jazzy 0.7.2

### ISSUE THREAD

**Issue by svdo** [CocoaPods/cocoadocs.org#476] opened 2016-10-19 19:40 UTC
My pod (NetUtils, v3.0.0 and v3.0.1) are not generating any documentation. After some digging, I found that the problem is that CocoaDocs uses jazzy 0.7.0. The new Swift 3 access control ('open', 'file_private') are not supported in that version, so jazzy errors out. 

Could you please update to jazzy 0.7.2? This fixes my issue, at least locally.

**Comment by r-dent** [comment] 2016-10-20 22:41
I have the same problem with [EliminationMenu](http://cocoadocs.org/docsets/EliminationMenu). 0% documentation does not look good. :-(

**Comment by segiddins** [comment] 2016-10-20 23:08
Please send a PR updating CocoaDocs :)

**Comment by r-dent** [comment] 2016-10-20 23:24
I just wanted to. But i found that according to the [Gemfile.lock](https://github.com/CocoaPods/cocoadocs.org/blob/master/Gemfile.lock#L6), you they are already using a version >0.7.2. 
So maybe there is something wrong with the deployment?

**Comment by orta** [comment] 2016-10-21 08:35
Closing as this is likely a dupe of https://github.com/CocoaPods/cocoadocs.org/issues/473 - CD is indeed on the latest Jazzy

**Closed by orta** 2016-10-21 08:35 UTC

**Comment by svdo** [comment] 2016-10-22 19:46
Issue solved, back at 100% documented, thanks! 👍
