### ISSUE TITLE
404, undefined method `split' for #<Array:0x007fbd1d81ad58>

### ISSUE THREAD

**Issue by kean** [CocoaPods/cocoadocs.org#362] opened 2015-06-29 18:57 UTC
Bug report

http://cocoadocs.org/docsets/DFImageManager/0.4.0
http://cocoadocs.org/docsets/DFCache/3.1.0

```
undefined method `split' for #<Array:0x007fbd1d81ad58>

/Users/maddern/dev/cocoadocs.org/classes/stats_generator.rb:76:in `generated_install_size'
/Users/maddern/dev/cocoadocs.org/classes/stats_generator.rb:24:in `upload'
/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:466:in `document_spec'
/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:513:in `document_spec_at_path'
/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:155:in `block in doc'
/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:150:in `each'
/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:150:in `doc'
/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:222:in `block in cocoadocs_url'
/Users/maddern/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:153:in `open_uri'
/Users/maddern/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:704:in `open'
/Users/maddern/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:34:in `open'
/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:219:in `cocoadocs_url'
/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:170:in `cocoadocs'
/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:114:in `initialize'
/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:532:in `new'
/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:532:in `<main>'
```

**Comment by segiddins** [comment] 2015-06-29 20:00
Duplicate of https://github.com/CocoaPods/cocoadocs.org/issues/361 which was fixed, but @orta just needs to redeploy.

**Closed by segiddins** 2015-06-29 20:00 UTC

**Comment by orta** [comment] 2015-06-30 08:42
sorry, been flying, will do now

**Comment by orta** [comment] 2015-06-30 08:43
updated it to latest, and set the last 3 days worth of pods re-parsing

**Comment by kean** [comment] 2015-06-30 09:30
Thanks a lot.
